version: '3.8'

services:
  chat-agent:
    build: .
    container_name: website-live-chat-agent
    ports:
      - "8000:8000"
    environment:
      # LLM 配置
      - LLM_PROVIDER=deepseek
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - DEEPSEEK_BASE_URL=https://api.deepseek.com/v1
      - DEEPSEEK_MODEL=deepseek-chat
      
      # LLM URL 配置（可选）
      # - LLM_BASE_URL_FIELD=${LLM_BASE_URL_FIELD}
      # - OPENAI_LLM_BASE_URL=${OPENAI_LLM_BASE_URL}
      # - DEEPSEEK_LLM_BASE_URL=${DEEPSEEK_LLM_BASE_URL}
      # - SILICONFLOW_LLM_BASE_URL=${SILICONFLOW_LLM_BASE_URL}
      # - ANTHROPIC_LLM_BASE_URL=${ANTHROPIC_LLM_BASE_URL}
      
      # Embedding 配置
      - EMBEDDING_PROVIDER=deepseek
      - EMBEDDING_MODEL=deepseek-embedding
      - EMBEDDING_DIM=1536
      
      # Embedding API Key 配置（可选）
      # - EMBEDDING_API_KEY_FIELD=${EMBEDDING_API_KEY_FIELD}
      # - OPENAI_EMBEDDING_API_KEY=${OPENAI_EMBEDDING_API_KEY}
      # - DEEPSEEK_EMBEDDING_API_KEY=${DEEPSEEK_EMBEDDING_API_KEY}
      # - SILICONFLOW_EMBEDDING_API_KEY=${SILICONFLOW_EMBEDDING_API_KEY}
      # - ANTHROPIC_EMBEDDING_API_KEY=${ANTHROPIC_EMBEDDING_API_KEY}
      
      # Embedding URL 配置（可选）
      # - EMBEDDING_BASE_URL=${EMBEDDING_BASE_URL}
      # - OPENAI_EMBEDDING_BASE_URL=${OPENAI_EMBEDDING_BASE_URL}
      # - DEEPSEEK_EMBEDDING_BASE_URL=${DEEPSEEK_EMBEDDING_BASE_URL}
      # - SILICONFLOW_EMBEDDING_BASE_URL=${SILICONFLOW_EMBEDDING_BASE_URL}
      # - ANTHROPIC_EMBEDDING_BASE_URL=${ANTHROPIC_EMBEDDING_BASE_URL}
      
      # Milvus 配置（已部署）
      - MILVUS_HOST=${MILVUS_HOST:-your-milvus-host}
      - MILVUS_PORT=${MILVUS_PORT:-19530}
      - MILVUS_USER=${MILVUS_USER:-root}
      - MILVUS_PASSWORD=${MILVUS_PASSWORD:-}
      - MILVUS_DATABASE=${MILVUS_DATABASE:-default}
      
      # Redis 配置
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      - REDIS_DB=0
      
      # API 配置
      - API_KEY=${API_KEY:-change-this-key}
      - CORS_ORIGINS=*
      
      # 应用配置
      - LOG_LEVEL=INFO
      - PORT=8000
      
      # LangGraph 配置
      - LANGGRAPH_MAX_ITERATIONS=10
      - LANGGRAPH_CHECKPOINTER=redis
      
      # 向量召回配置
      - VECTOR_TOP_K=3
      - VECTOR_SCORE_THRESHOLD=0.7
      - VECTOR_CHUNK_SIZE=500
      - VECTOR_CHUNK_OVERLAP=50
      
      # 消息过滤配置
      - MESSAGE_FILTER_ENABLED=true
      - MESSAGE_MAX_LENGTH=1000
      - INSTRUCTION_KEYWORDS=You are an AI,Your role is to,Follow these guidelines,Use user's language,Always return,Always wrap,You are a helpful assistant,Your task is to,Please rephrase,Convert the following,Transform this query
      - TECHNICAL_TERMS_THRESHOLD=3
      - TECHNICAL_TERMS=API,endpoint,function,method,parameter,response,request
      
      # 管理员认证配置
      - ADMIN_USERNAME=${ADMIN_USERNAME:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-change_me_in_production}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-your-secret-key-min-32-chars-long}
      - JWT_EXPIRE_MINUTES=${JWT_EXPIRE_MINUTES:-60}
      
      # PostgreSQL 配置
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=${POSTGRES_DB:-chat_agent_admin}
      - POSTGRES_USER=${POSTGRES_USER:-admin}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-your_postgres_password}
    
    depends_on:
      - redis
      - postgres
    
    restart: unless-stopped
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  redis:
    image: redis:7-alpine
    container_name: chat-agent-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    container_name: chat-agent-postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-chat_agent_admin}
      - POSTGRES_USER=${POSTGRES_USER:-admin}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-your_postgres_password}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-admin} -d ${POSTGRES_DB:-chat_agent_admin}"]
      interval: 10s
      timeout: 5s
      retries: 5

  admin-frontend:
    build: ./admin-frontend
    container_name: chat-agent-admin-frontend
    ports:
      - "3000:80"
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
    depends_on:
      - chat-agent
    restart: unless-stopped

volumes:
  redis-data:
  postgres-data:

